org: stamtech
app: shogun
# serverless.yml
service: shogun-backend
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-1:*:*"

functions:
  cardDivision: # Function name
    handler: ./cardDivision/index.default
    events: # All events associated with this function
      - http:
          path: cardDivision/get-cards
          method: get
