org: stamtech
app: shogun
# serverless.yml
service: shogun-backend
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: !GetAtt ShogunTable.Arn

functions:
  cardDivision: # Function name
    handler: ./cardDivision/index.default
    events: # All events associated with this function
      - http:
          path: cardDivision/get-cards
          method: get

resources:
  Resources:
    ShogunTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: game
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
